### ISSUE TITLE
Error message is unclear

### ISSUE THREAD

**Issue by lestrrat** [goccy/go-json#106]
> "failed to handle opcode. doesn't implement %s"

このメッセージは英語で読むとちょっと意味が通りづらいと思います。

まず多分言いたいのは「このオペコードは実装されていない」だと思うんですけど、主語が抜けているためtype がinterfaceをimplementするのimplementなのか、実装されていない、の実装なのかよくわからないです。

おすすめは

> opcode %s has not been implemented for %s

で、二つ目の%sには対象のオブジェクトないしフィールド名が表示できると最高だと思います。

また、同じメッセージが4カ所に登場するのもデバッグを難しくしていると思うので、それぞれのメッセージの最初にコンテキスト固有のなにがしかを追加するといいかと思います。

> encoder (escaped): opcode %s has not been implemented for %s

とか。

二つ目の%sを端折るなら

> encoder (escaped): opcode %s has not been implemented

でもいいかと思います。

**Comment by goccy** [comment]
ありがとうございます。

https://github.com/goccy/go-json/pull/107/commits/04da39a443d87164a2b094e1162600cdd672e08d

こちらで修正しました！
