### ISSUE TITLE
consolidate matching tokens

### ISSUE THREAD

**Issue by lestrrat** [goccy/go-json#109]
最初は `len(buf)`と`curso`rを比較しないで `buf[cursor]` してるところが危ないな〜と思ってコードを見ていたのですが、気づいたら 'n', 'u', 'l', 'l' を探して比較している全く同じコードが数カ所にあったので一カ所にまとめてみました。

https://github.com/lestrrat-go/go-json/commit/4c8d8ff1361242cbf263ce076928bb6c078c8ba0

こんな感じの変更をしてよければ、他の"true", "false"とかのトークンも似たようにマッチするコードを追加しますが、いかがでしょう

**Comment by goccy** [comment]
`len(buf)` と `cursor` を比較していないのは高速化のテクニックで、 buf の末尾に NUL 文字を足しているので、
`buf[cursor]` の switch-case の中に `NUL` が含まれていればバッファの終端を検知できるというのでやってます。

処理の共通化とかのリファクタリングは、この後自分の方でやる予定なのでいったん大丈夫です！
今は可読性より速度を優先していて、 `encoding/json` にある全テストケースを通したら(今は一部のテストが通っていません)、速度を劣化させずにリファクタリングしていこうと思っています。

**Comment by lestrrat** [comment]
nrhdでは一旦こちらわすれますー
