### ISSUE TITLE
Invalid JSON produced when embedding structs

### ISSUE THREAD

**Issue by nsf** [goccy/go-json#116]
Hi, tried your lib on a fairly large project. Was able to make a reproducable example where lib produces incorrect JSON, here it is:

```go
package main

import (
	"fmt"
	"github.com/goccy/go-json"
)

type Boo struct{ B string }
type Struct struct {
	A   int
	Boo *Boo
}
type Embedded struct {
	Struct
}

func main() {
	e := Embedded{Struct: Struct{
		A:   1,
		Boo: &Boo{B: "foo"},
	}}
	data, err := json.Marshal(e)
	fmt.Println(err)
	fmt.Println(string(data))
}
```
Prints:
```
<nil>
{"A":1,"Boo":"B":"foo"}
```
Note that Boo is lacking braces `{}`. And this is what "encoding/json" produces:
```
{"A":1,"Boo":{"B":"foo"}}
```

---

And a bonus problem, while I was trying to make a reproducable case, I noticed that if you rename Boo field above to just B, e.g.
```go
package main

import (
	"fmt"
	"github.com/goccy/go-json"
)

type Boo struct{ B string }
type Struct struct {
	A int
	B *Boo
}
type Embedded struct {
	Struct
}

func main() {
	e := Embedded{Struct: Struct{
		A:   1,
		B: &Boo{B: "foo"},
	}}
	data, err := json.Marshal(e)
	fmt.Println(err)
	fmt.Println(string(data))
}
```
Library stops marshalling that field completely:
```
<nil>
{"A":1}
```
What "encoding/json" lib produces:
```
{"A":1,"B":{"B":"foo"}}
```

**Comment by goccy** [comment]
Thank you for reporting !! I fixed this issue with #117 and released as v0.4.1
