### ISSUE TITLE
Pointer corruption during decoding

### ISSUE THREAD

**Issue by dynamix** [goccy/go-json#166]
While testing goccy/go-json (v0.4.8) as easyjson replacement with a larger project, tests in our test suite would fail unpredictably. Goccy/go-json was used only for unmarshaling. It looks like pointers get mixed up / corrupted sometimes, resulting in either invalid data, panics or errors when the GC detects pointers to released memory.    

For one case I managed to write a test to reproduce the behaviour. 

```
package main

import (
	"fmt"

	"github.com/goccy/go-json"
)

type B struct{ Int int32 }

type A struct{ B *B }

type X struct{ A []*A }

func main() {

	w1 := &X{}
	w2 := &X{}

	json.Unmarshal([]byte(`{"a": [ {"b":{"int": 42} } ] }`), w1)
	fmt.Printf("%p => %d\n", &w1.A[0].B.Int, w1.A[0].B.Int)

	json.Unmarshal([]byte(`{"a": [ {"b":{"int": 112} } ] }`), w2)
	fmt.Printf("%p => %d\n", &w1.A[0].B.Int, w1.A[0].B.Int)
	fmt.Printf("%p => %d\n", &w2.A[0].B.Int, w2.A[0].B.Int)

}
```

Output
```
x1 0xc0000ae084 => 42
x1 0xc0000ae084 => 112
x2 0xc0000ae084 => 112
```

All `B`s seem to point to the same address but they should not. Unmarshalling the second JSON string into `x2` overrides data in `x1`

**Comment by goccy** [comment]
Thank you for the great report !!! I fixed this issue with #167 .
