### ISSUE TITLE
Add go-fuzz support?

### ISSUE THREAD

**Issue by aaron42net** [goccy/go-json#174]
I tried to use `go-json` with large codebase that's currently using `segmentio/encoding/json` and found that a number of tests failed based on what appeared to be subtle bugs in input handling. This suggests that `go-json` has not been subjected to [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) to shake out input-handling bugs and therefore might not be safe to handle untrusted input.  Looking through the issue tracker for `go-json` suggests many of the issues have been around crashes or similar, which seems to confirm this.

Have you considered adding support for `go-fuzz` and fixing issues it finds?  There's code to test `encoding/json` and a starting corpus based on exercising codepaths in it at https://github.com/dvyukov/go-fuzz-corpus/blob/master/json that might be useful.

Alternatively, https://github.com/segmentio/encoding/tree/master/json/fuzz uses a fork of this to find differences between the segment.io json implementation and `encoding/json`.  What guarantees does go-json want to provide around differences from encoding/json?  Are you willing to consider cases where encoding/json can unmarshal but go-json returns an error or vice-versa a bug?

In playing around with a fork of https://github.com/segmentio/encoding/tree/master/json/fuzz locally, it seems to have found some issues after running for a few hours on my laptop, even after relaxing the guarantee about error messages exactly matching.

Do you want to play around with this yourselves?  Or can I offer the fuzz package as a PR?  It would be Apache 2 licensed, with a copyright of "go-fuzz project authors".

I can also attempt to turn its output into individual bugs reports, but I suspect that path will be slower and incomplete.

Let me know how you want to proceed.  Thanks!

-- Aaron

**Comment by goccy** [comment]
I was just thinking of running a fuzzing test to ensure that I got the same output as encoding/json.
I have no intention of changing the license from MIT.

**Comment by aaron42net** [comment]
segmentio is also MIT, and they've confined the go-fuzz code to a subdirectory, left the original copyright in place and put its separate LICENSE in that subdirectory.  This seems to be the established pattern for importing third-party code into an open source project while not making any claims to its copyright or attempting to change its license.  I don't know if you'd be comfortable doing similarly.

The fuzzing function isn't very big, so you could certainly do your own implementation if that's a problem.

**Comment by goccy** [comment]
I added documentation for fuzzing to the README.md ( FYI: https://github.com/goccy/go-json/blob/master/README.md#fuzzing ) . Please see it.

The implementation for fuzzing has separated the repositories. You can find it [here](https://github.com/goccy/go-json-fuzz).
