### ISSUE TITLE
Ideas for unique features

### ISSUE THREAD

**Issue by goccy** [goccy/go-json#178]
This issue is to summarize go-json's unique features that we plan to implement in the future.

# Features

## `context.Context` support for `Marshaler` and `Unmarshaler` 

I plan to provide the two APIs follows:

-  `json.MarshalContext(context.Context, interface{}, ...json.EncodeOption) ([]byte, error)`
- `json.UnmarshalContext(context.Context, []byte, interface{}, ...json.DecodeOption) error`

Then, if we implemented the following interface, callback it.

```go
type MarshalerContext interface {
  MarshalJSON(context.Context) ([]byte, error)
}

type UnmarshalerContext interface {
  UnmarshalJSON(context.Context, []byte) error
}
```

### Why

I thought there were situations in `MarshalJSON` and `UnmashalJSON` where I wanted to use `context.Context` .

For example, we consider the situation that in MarshalJSON, you want to access external middleware, get the data, and then encode it. At this time, `context.Context` may be required when accessing middleware, we want to use the `context.Context` not created inside `MarshalJSON` but used by the caller of `json.Marshal()`. 
I show this situation's sample code the following:

```go

type User struct {
  ID int64
  Name string
  UserAddress UserAddressResolver
}

type UserAddressResolver func(ctx context.Context) (*UserAddress, error)
func (r UserAddressResolver) MarshalJSON() ([]byte, error) {
  ctx := context.Background() // we want to use parent context.Context but we can't get it.
  address, err := r(ctx) // fetch UserAddress data from external middleware
  if err != nil {
    return nil, err
  }
  return json.Marshal(address)
}

type UserAddress struct {
  ID int64
  UserID int64
  PostCode string
  Address string
}

u := &User{ID: 1, Name: "alice"}
u.UserAddress = func(ctx context.Context) (*UserAddress, error) {
  return db.FindUserAddressByUserID(ctx, u.ID)
}

json.Marshal(u)
```

In this case, there is no way to pass context.Context to MarshalJSON , so I think that an approach like json.MarshalContext is necessary.

**Comment by goccy** [comment]
# Decoding process using JSONPath

## json.PathString

```go
type PathString string
```

`PathString` represents JSONPath.
JSONPath rules are determined based on https://goessner.net/articles/JsonPath ,
We are also considering accepting more flexible expressions. (For example, do not require root `$ .`)

## json.UnmarshalPath

```go
func UnmarshalPath(src []byte, path PathString, dst interface{}) error
func UnmarshalPathContext(ctx context.Context, src []byte, path PathString, dst interface{}) error
```

`json.UnmarshalPath`,` json.UnmarshalPathContext` use `PathString` to provide the ability to save only where you need it.

### Example

```go
var b string
if err := json.UnmarshalPath([]byte(`{"a":{"b":"c"}}`), "a.b", &b); err != nil {
  panic(err)
}
```

## json.UnmarshalPaths

```go
type PathMap map[PathString]interface{}

func UnmarshalPaths(src []byte, paths json.PathMap) error
func UnmarshalPathsContext(ctx context.Context, src []byte, paths json.PathMap) error
```

`json.UnmarshalPaths`,` json.UnmarshalPathsContext` provides the ability to retrieve only the parts you need at once using multiple paths.

### Example

```go
var (
  b string
  c int
)
if err := json.UnmarshalPaths([]byte(`{"a":{"b":"str", "c": 1}}`), json.PathMap{
  "a.b": &b,
  "a.c": &c,
}); err != nil {
  panic(err)
}
```

## json.(*Decoder).DecodePath

```go
func (d *Decoder) DecodePath(path PathString, v interface{}) error
func (d *Decoder) DecodePathContext(ctx context.Context, path PathString, v interface{}) error
```

`DecodePath`,` DecodePathContext` provides the same functionality as `UnmarshalPath` that can be applied to stream processing.

### Example

```go
dec := json.NewDecoder(strings.NewReader(`{"a":{"b":"c"}}`))

var b string
if err := dec.DecodePath("a.b", &b); err != nil {
  panic(err)
}
```

## json.(*Decoder).DecodePaths

```go
func (d *Decoder) DecodePaths(paths PathMap) error
func (d *Decoder) DecodePathsContext(ctx context.Context, paths PathMap) error
```

`DecodePaths`,` DecodePathsContext` provides the same functionality as `UnmarshalPaths` that can be applied to stream processing.

### Example

```go
dec := json.NewDecoder(strings.NewReader(`{"a":{"b":"str", "c": 1}}`))

var (
  b string
  c int
)
if err := dec.DecodePaths(json.PathMap{
  "a.b": &b,
  "a.c": &c,
}); err != nil {
  panic(err)
}
```

## json.Get

```go
func Get(src interface{}, path PathString, dst interface{}) error
```

`Get` provides the ability to filter already retrieved values ​​using `PathString` and store those values ​​in dst.
You can efficiently acquire the value when you want to switch the value to be filtered after seeing the acquired value.

### Example

```go
var v interface{}
if err := json.Unmarshal([]byte(`{"a":{"b":"c"}}`), &v); err != nil {
  panic(err)
}

var b string
if err := json.Get(v, "a.b", &b); err != nil {
  panic(err)
}

var c int
if err := json.Get(v, "a.c", &c); err != nil {
  panic(err)
}
```

## json.Gets

```go
func Gets(src interface{}, path PathMap) error
```

`Gets` provides the same functionality as` Get`, but you can use multiple paths in your filter.

### Example

```go
var v interface{}
if err := json.Unmarshal([]byte(`{"a":{"b":"str", "c": 1}}`), &v); err != nil {
  panic(err)
}

var (
  b string
  c int
)
if err := json.Gets(v, json.PathMap{
  "a.b": &b,
  "a.c": &c,
}); err != nil {
  panic(err)
}
```

## json.Path

```go
func (p PathString) Build() (*Path, error)

type Path struct {}

func (p *Path) Get(src interface{}, dst interface{}) error
```

You can skip the process of building Path by creating a `Path` instance from `PathString` with the `Build()`, caching, and reusing it. This allows for efficient `Get` operations.

### Example

```go
var v interface{}
if err := json.Unmarshal([]byte(`{"a":{"b":"c"}}`), &v); err != nil {
  panic(err)
}

path, err := json.PathString("a.b").Build()
if err != nil {
  panic(err)
}

var b string
if err := path.Get(v, &b); err != nil {
  panic(err)
}
```

**Comment by goccy** [comment]
# Colorize the JSON string

We recognize that there is a demand for colorize the JSON string, mainly in Logger.
However, when coloring using escape sequences, if you try to do the processing outside the JSON library, you need to hook by `MarshalJSON`, which slows down the speed.

Therefore, if go-json will support colorize the JSON string, which makes it possible to colored JSON string at high speed. For example, we are considering the following API.

```go
type ColorScheme struct {
  Key string
  Delim string
  Int string
  ...
}

var DefaultColorScheme = ColorScheme{
  Key: "",
  ...
}
func Colorlize(enabled bool, ColorScheme) func(EncodeOption) EncodeOption
```

```go
v := struct{
  A string
  B int
}{A: "str": B: 10}

coloredBytes, err := json.MarshalWithOptions(v, json.Colorize(true, json.DefaultColorScheme))
if err != nil {
  panic(err)
}
logger.Info(coloredBytes) // pass colored buffer to the logger
```

You can control whether to color or not with Option, so you can also combine it with `json.MarshalIndent` and` json.(*Encoder)`.

**Comment by jxskiss** [comment]
Seeing the above **"Decode with JSONPath"**,
I have a little question, there seems exist several json libraries solved this problem and some have high performance, so why we need a new one and what difference will it provide?

**Comment by jxskiss** [comment]
For feature beyond the std lib, I'd like there be some way to disable HTML escaping, for readability of logging messages~
Or a function which provides reasonable settings for logging messages.

**Comment by jxskiss** [comment]
Another usecase, a custom way may be provided to marshal maps without sorting keys for even better performance. Maps are used so commonly in every application, sometimes map key ordering just don't matter.

**Comment by goccy** [comment]
@jxskiss 

- A1
 
As far as I know, decoding using JSONPath is required by many users. I think this feature should be in the standard library. Also, there are other JSON libraries that use JSONPath, but I don't think they have sufficient performance.
Finally, implementing JSONPath is easy for me :)

- A2

`encoding/json` and `goccy/go-json` are both has a `SetEscapeHTML(bool)` API in stream encoder .

- A3

`goccy/go-json` already has been supported unordered map for encoding as `json.UnorderedMap()` option

**Comment by jxskiss** [comment]
@goccy Great you have done the context support feature!
Small questions about naming:
1. the `MarshalerContext` and `UnmarshalerContext` sounds like something more related to a "Context" but not Marahsler/Unmarshaler, would it be a litte better for something like "ContextAwareMarshaler" and "ContextAwareUnmarshaler"?
2. the methods of the interface use same names with `json.Marshaler` and `json.Unmarshaler` (MarshalJSON and UnmarshalJSON), which means a type can't implement both interface at same time, is it by purpose and what's the consideration behind?

**Comment by goccy** [comment]
@jxskiss 
> the MarshalerContext and UnmarshalerContext sounds like something more related to a "Context" but not Marahsler/Unmarshaler, would it be a litte better for something like "ContextAwareMarshaler" and "ContextAwareUnmarshaler"?

It's difficult to name, but I chose a simpler name ( just added Context to Marshaler / Unmarshaler ).

> the methods of the interface use same names with json.Marshaler and json.Unmarshaler (MarshalJSON and UnmarshalJSON), which means a type can't implement both interface at same time, is it by purpose and what's the consideration behind?

This is because there is no merit to coexist with and without context.Context.
I decided that the same method name would be better so that I wouldn't be confused as to which one would be called.
