### ISSUE TITLE
go-json Marshal ignores omitempty struct tag

### ISSUE THREAD

**Issue by Kiraub** [goccy/go-json#179]
**go version**: `go1.16.3 windows/amd64`
**go-json version**: `github.com/goccy/go-json v0.4.11`

**What happened?**

While searching for the cause of an indentation conflict between the standard module and this one, i came across this behaviour that `go-json` will ignore the `json:",omitempty"` struct tag when calling `Marshal()`. It will instead give the field a default zero-value.

**How to reproduce?**

Execute the following test with `go-json` imported as `json` and `encoding/json` imported as `jsonStd`:

*EDIT: Updated Test for more types
```go
func TestCompareJSONModules(t *testing.T) {
	var exampleJSON, exampleJSONStd struct {
		T struct {
			T1 bool        `json:"t1,omitempty"`
			T2 float64     `json:"t2,omitempty"`
			T3 string      `json:"t3,omitempty"`
			T4 []string    `json:"t4,omitempty"`
			T5 *struct{}   `json:"t5,omitempty"`
			T6 interface{} `json:"t6,omitempty"`
		} `json:"t"`
	}
	jsonExample := `{
	"t": {
		"t1": false,
		"t2": 0,
		"t3": "",
		"t4": [],
		"t5": null,
		"t6": null
	}` + "\n}"
	_ = json.Unmarshal([]byte(jsonExample), &exampleJSON)
	_ = jsonStd.Unmarshal([]byte(jsonExample), &exampleJSONStd)
	bJSON, _ := json.Marshal(exampleJSON)
	bJSONStd, _ := jsonStd.Marshal(exampleJSONStd)
	sJSON := string(bJSON)
	sJSONStd := string(bJSONStd)
	if sJSON != sJSONStd {
		t.Fatalf("conflict:\ngo-json:\n%#v\nencoding/json:\n%#v\n", sJSON, sJSONStd)
	}
}
```

The output should look something like:

```
conflict:
go-json:
"{\"t\":{\"t4\":[],\"t6\":null}}"
encoding/json:
"{\"t\":{}}"
```

**Comment by goccy** [comment]
@Kiraub Thank you for the great reporting ! I fixed this issue with #183
