### ISSUE TITLE
Set max size when reading

### ISSUE THREAD

**Issue by stuartnelson3** [goccy/go-json#192]
I'm attempting to limit the amount of bytes read per call to `decoder.Decode` with a `bufio.NewReaderSize`:

```go
bufioReader := bufio.NewReaderSize(r, size)
decoder := json.NewDecoder(bufioReader)
```

When I decode json, however, it is decoding the entire line:

```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"strings"

	"github.com/goccy/go-json"
)

func main() {
	const jsonStream = `
	{"Name": "Sam", "Text": "Who's there?"}
	{"Name": "Ed", "Text": "Go fmt."}
	{"Name": "Sam", "Text": "Go fmt who?"}
	{"Name": "Ed", "Text": "Go fmt yourself!"}
`
	type Message struct {
		Name, Text string
	}
	var r io.Reader
	r = strings.NewReader(jsonStream)
	r = bufio.NewReaderSize(r, 8)
	dec := json.NewDecoder(r)
	for {
		var m Message
		if err := dec.Decode(&m); err == io.EOF {
			break
		} else if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%s: %s\n", m.Name, m.Text)
	}
}
```
Is there any way to enforce this within the library, so that if if a line of JSON is too long, the decoder will error out and move on to the next line?

**Comment by goccy** [comment]
As with encoding/json, the Decode API doesn't finish until the value to be decoded is read.
So even if the unit to read is small, the buffer will increase.
Perhaps in this case it is better to use the Token API.
