### ISSUE TITLE
Bug in nullBytes(), trueBytes() and falseBytes() overwriting unparsed buffer space

### ISSUE THREAD

**Issue by DasSkelett** [goccy/go-json#196]
Discovered while trying to debug the cause for huge memory consumption by go-json, more on that in a separate issue.

## Problem
At the beginning of `nullBytes()`, `trueBytes()` and `falseBytes()`, the code checks whether the buffer has still enough data in it left to read the whole token (`null`/`true`/`false`). If not, it tries to read more from the reader:
https://github.com/goccy/go-json/blob/4d51b8b764e125e7f6715e037b196210d81c5ee4/decode_string.go#L236-L241
https://github.com/goccy/go-json/blob/4d51b8b764e125e7f6715e037b196210d81c5ee4/decode_bool.go#L16-L21
https://github.com/goccy/go-json/blob/4d51b8b764e125e7f6715e037b196210d81c5ee4/decode_bool.go#L38-L43

There's two problems with that:

### Overwriting remaining buffer data
`s.read()` overwrites everything in the buffer from the current cursor onwards. See `s.readBuf()`, it returns a slice beginning from the current cursor position:
https://github.com/goccy/go-json/blob/4d51b8b764e125e7f6715e037b196210d81c5ee4/decode_stream.go#L67
...in which the new data is read next:
https://github.com/goccy/go-json/blob/4d51b8b764e125e7f6715e037b196210d81c5ee4/decode_stream.go#L77

if the cursor isn't at the very last position of the remaining data in the buffer (`s.length-1`, I think), everything from the cursor position onwards gets overwritten and is lost.
This is the case in `nullBytes()`, `trueBytes()` and `falseBytes()`, it looks ahead and reads new data while the cursor isn't at the end of the current data left in the buffer.

### Potentially insufficient data read from stream
These functions only call `s.Read()` once, however `s.Read()` isn't guaranteed to read enough bytes to include the entire value. An `io.Reader`, can very well only return 1 char, or even 0 (even though that's discouraged):
> If some data is available but not len(p) bytes, Read conventionally returns what is available instead of waiting for more. 
> Implementations of Read are discouraged from returning a zero byte count with a nil error, except when len(p) == 0. Callers should treat a return of 0 and nil as indicating that nothing happened; in particular it does not indicate EOF. 

https://golang.org/pkg/io/#Reader

Instead, in places like these, `s.read()` should be called in a loop, until it either has read enough chars to fit the entire expected value, or it returns `false` due to an unexpected `EOF` or whatever.

This also touches the memory consumption problem I have, but I'll open a separate issue for that, with some pprof data and a reproduction benchmark if I can get one to work.

**Comment by goccy** [comment]
Thank you for the reporting ! Could you please share reproducible code ?

**Comment by goccy** [comment]
I understood your point. I will fix this.

**Comment by DasSkelett** [comment]
Sorry, I was busy otherwise, so I didn't have time to prepare some code.
But I can confirm that #208 is looking good, and the test from #199 was exactly how I'd have crafted the JSON,
that is placing a `null` (or `true` or `false`) right around the 1024th char, so that it begins within the initial buffer (which is `2*initBufSize` long, but ends afterwards.
