### ISSUE TITLE
Unmarshaling a "null" into a []byte results in an empty slice instead of "nil" (differs from encoding/json)

### ISSUE THREAD

**Issue by zimmski** [goccy/go-json#203]
The following reproducer shows that unmarshaling of a "null" into a byte slice gives a different result than encoding/json. This was also the case with 4d51b8b (before https://github.com/goccy/go-json/pull/198) and does not change with https://github.com/goccy/go-json/pull/200

```
package main

import (
	"encoding/json"
	"fmt"
	"os"

	gojson "github.com/goccy/go-json"
)

type SomeStruct struct {
	Data []byte
}

func main() {
	original := []byte(`{"Data":null}`)

	validEncodingJSON := json.Valid(original)
	validGoJSON := gojson.Valid(original)

	fmt.Printf("%v vs %v\n", validEncodingJSON, validGoJSON)
	if validEncodingJSON != validGoJSON {
		fmt.Println("ERROR: Unequal \"Valid\" results")

		os.Exit(1)
	}

	var resultEncodingJSON SomeStruct
	if err := json.Unmarshal(original, &resultEncodingJSON); err != nil {
		panic(err)
	}
	resultEncodingJSONString := fmt.Sprintf("%#v", resultEncodingJSON)
	fmt.Println(resultEncodingJSONString)

	var resultGoJSON SomeStruct
	if err := gojson.Unmarshal(original, &resultGoJSON); err != nil {
		panic(err)
	}
	resultGoJSONString := fmt.Sprintf("%#v", resultGoJSON)
	fmt.Println(resultGoJSONString)

	if resultEncodingJSONString != resultGoJSONString {
		fmt.Println("ERROR: Unequal \"Unmarshal\" results")

		os.Exit(1)
	}
}
```

results in

```
true vs true
main.SomeStruct{Data:[]uint8(nil)}
main.SomeStruct{Data:[]uint8{}}
ERROR: Unequal "Unmarshal" results
exit status 1
```

**Comment by zimmski** [comment]
This might be one of the last probems in our regular unit tests @symflower. I kind of think that this is related to https://github.com/goccy/go-json/issues/201 because i guess that there should be a fast-path for when the data is "null".

Since it do not know the code that well i will focus on reproducers for now. Let me know if i should take a deeper look though. Will now investigate a failure in our integration test suite which looks like a different problem.

**Comment by zimmski** [comment]
One of our integration tests went from about ~260seconds to about 210seconds by switching from encoding/json to go-json. Need to further benchmark to get a reliable number but even a 10sec boost is a win on our side. 50seconds would be amazing :-)

**Comment by zimmski** [comment]
@goccy don't know where to post this. I have a successful CI pipeline now with our monorepo. The integration tests where unfortunately not reliable. Improvement ranges in a few seconds. Looks like that we already merged a lot of improvements that migrate away from JSON. However, there are lots of JSON calls left so i added a small benchmark with two typical types of objects so we can track improvements with this package more reliable.

```
BenchmarkJSON/encoding/json/MarshalSymbol-8                  728           1509156 ns/op          302392 B/op       1107 allocs/op
BenchmarkJSON/encoding/json/UnmarshalSymbol-8                956           1180351 ns/op         1074461 B/op       2529 allocs/op
BenchmarkJSON/encoding/json/MarshalDependency-8               24          45716376 ns/op        14760109 B/op      48882 allocs/op
BenchmarkJSON/encoding/json/UnmarshalDependency-8             16          68107645 ns/op        86285247 B/op     224862 allocs/op
BenchmarkJSON/go-json/MarshalSymbol-8                       1392            810509 ns/op          333393 B/op       1381 allocs/op
BenchmarkJSON/go-json/UnmarshalSymbol-8                     2688            461234 ns/op          493600 B/op       3949 allocs/op
BenchmarkJSON/go-json/MarshalDependency-8                     34          31824248 ns/op        16521427 B/op      61091 allocs/op
BenchmarkJSON/go-json/UnmarshalDependency-8                   28          43814366 ns/op        33977350 B/op     350604 allocs/op
BenchmarkJSON/segmentio/encoding/json/MarshalSymbol-8        900           1321053 ns/op          296858 B/op       1106 allocs/op
BenchmarkJSON/segmentio/encoding/json/UnmarshalSymbol-8     1222            945775 ns/op         1073735 B/op       2520 allocs/op
BenchmarkJSON/segmentio/encoding/json/MarshalDependency-8     24          44625790 ns/op        13598500 B/op      48856 allocs/op
BenchmarkJSON/segmentio/encoding/json/UnmarshalDependency-8   19          62479233 ns/op        86288995 B/op     224841 allocs/op
```

As you can see there is a good improvement and it adds up

**Comment by zimmski** [comment]
@goccy please let me know if you need anything else. I think the changes of  the last days are worth issuing a new release. I will then move the changes into testing on our side. Will let you know if some problem turns up.

**Comment by goccy** [comment]
Thank you. I'm planning to make a new release today.
