### ISSUE TITLE
Random seg fault on Unmarshal

### ISSUE THREAD

**Issue by zeripath** [goccy/go-json#275]
Hi!

This is quite a strange one... I've not completely minimized the testcase yet but it's possible to get a segfault when unmarshalling into a non empty struct slice.

[goccytest-smaller.go.txt](https://github.com/goccy/go-json/files/6976849/goccytest-smaller.go.txt)

The attached file unmarshals three strings on to an array, the third time causes a segfault. All three must be present to cause the segfault - drop one or rearrange them and the segfault goes away...

**Comment by goccy** [comment]
I fixed this issue with #276 🎉

**Comment by zeripath** [comment]
Great!

Our automated tests now pass on go-json. I think we need to do a bit more non automated testing and maybe add some different error handling though but genuinely it's looking good.
