### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by tfzxyinhao** [goccy/go-json#289]
`go build github.com/goccy/go-json/internal/encoder/vm: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed`
similar to https://github.com/goccy/go-json/issues/139
go-json version v0.7.8
does anyone knows to solive this compile error

my go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2470547771=/tmp/go-build -gno-record-gcc-switches"

**Comment by goccy** [comment]
This error depends on the amount of memory resources in your build environment.
If it is about 1GB, the error will not appear.

**Comment by emad-elsaid** [comment]
we faced this same issue, we had 1GB for the process but not dedicated to just json parsing. and we get OOM.
