### ISSUE TITLE
Error on non existing `map[float64]float64` json key

### ISSUE THREAD

**Issue by rustatian** [goccy/go-json#320]
Hey @goccy, thanks for the nice library 👍🏻 

I have an issue with parsing the `map[float64]float64` fields.

Given the following example (simplified):

```go
package main

import (
	"github.com/goccy/go-json"
)

type Foo struct {
	Bar map[float64]float64 `json:"bar,omitempty"`
}

func main() {
	data := []byte(`{"name":"test"}`)

	nc := &Foo{}

	err := json.Unmarshal(data, nc)
	if err != nil {
		panic(err)
	}
}
```

error: `json: cannot unmarshal object into Go struct field Foo.Bar of type float64`.

In this case, there is no such key `bar` in the incoming JSON. I expect, that the structure will have just `nil` `Bar` field w/o errors, instead, in the case of `map[float64]float64` I get an error.

I guess, that happens because there is no case for the `*decoder.floatDecoder` in the `internal/decoder/compile.go` `compileMapKey` function.

**Comment by goccy** [comment]
Thank you for reporting ! I'll fix this problem with #321
