### ISSUE TITLE
Unmarshal hangs on large dataset

### ISSUE THREAD

**Issue by brightpuddle** [goccy/go-json#333]
I have a large dataset that takes an extraordinarily long time Unmarshalling into a `map[string]struct`. The same data decodes fine, and fairly quickly with encoding/json. Doing some testing it seems to get considerably slower as the size of the dataset increases. The original dataset is 369,401 lines, but as an example these are the results of timing the binary on my laptop at 100,000 lines:

**go-json**
`./go-json-test  13.96s user 0.05s system 99% cpu 14.016 total`

**encoding/json**
`./go-json-test  0.08s user 0.01s system 23% cpu 0.385 total`

The numbers diverge further the larger the dataset. I've never waited for long enough for the original, full dataset to complete, so not sure how long it takes.

Tested on Go 1.17.6 on MacOS Monterey (12.1) and Go 1.17.7 on Debian Sid (unstable).

I've created a minimal reproduction of the problem including the full, original dataset here:

https://github.com/brightpuddle/go-json-test

**Comment by orisano** [comment]
The cause is probably the same as #306.

**Comment by orisano** [comment]
<img width="1307" alt="Screen Shot 2022-02-12 at 14 12 08" src="https://user-images.githubusercontent.com/1029249/153697734-b6a570c1-6e74-4a09-b700-981b981fbcce.png">
