### ISSUE TITLE
[QUESTION] - Different error message from standard json

### ISSUE THREAD

**Issue by sujit-baniya** [goccy/go-json#336]
Almost all error messages are different from standard json. Shouldn't it require to have same error messages to be 100% compatible?

**Comment by sujit-baniya** [comment]
```go
package main

import (
	stdJson "encoding/json"
	"github.com/goccy/go-json"
)

type User struct {
	ID map[string]int `json:"id"`
}

func main() {
	goccyJson()
	// testStdJson()
}

func testStdJson() {
	data := []byte(`{"id": 1}`)
	var user User
	err := stdJson.Unmarshal(data, &user)
	if err != nil {
		panic(err)
	}
}

func goccyJson() {
	data := []byte(`{"id": 1}`)
	var user User
	err := json.Unmarshal(data, &user)
	if err != nil {
		panic(err)
	}
}
```
![image](https://user-images.githubusercontent.com/4959215/154684793-f787118f-8d5a-40c0-8a9e-38979438a370.png)

**Comment by goccy** [comment]
We're aiming for behavior that's compatible with encoding/json, but it doesn't include outputs the exact same error message. So, this is spec .
However, we plan to make corrections to change the error message to a more understandable one in the future.
