### ISSUE TITLE
 not work on go 1.18

### ISSUE THREAD

**Issue by luyouxin84** [goccy/go-json#346]
i use framework go fiber, fiber.Context.Json cant work.
in go 1.17.8 c.json work fine,but after i upgrade go version , c.Json not work report "runtime error empty pointer"

they asked me send here. can u check this?

**Comment by DasSkelett** [comment]
Downstream issue: https://github.com/gofiber/fiber/issues/1820

**Comment by goccy** [comment]
Thank you for reporting. I'll try to support Go 1.18.

**Comment by goccy** [comment]
First, I updated go version with #347 , But doesn't seem to reproduce in my test case. 
Could you provide the minimum reproducible code ?

**Comment by efectn** [comment]
I think you can close the issue. Probably it was related of using Fiber version.

**Comment by goccy** [comment]
Thank you :)

If you have any problems, please reopen this issue .
