### ISSUE TITLE
zero byte in error string

### ISSUE THREAD

**Issue by jfcg** [goccy/go-json#354]
Hi,
For Go `1.17.8` and go-json `0.9.6` this code:
```go
package main

import (
	"fmt"
	"github.com/goccy/go-json"
)

func main() {
	buf := []byte{}
	obj := struct{ X int }{}

	if err := json.Unmarshal(buf, &obj); err != nil {
		s := err.Error()
		fmt.Println(s)
		fmt.Println(s[19])
	}
}
```
prints:
```
invalid character '' looking for beginning of value
0
```
so there is a zero byte between single quotes in the error message. This does not sound right as there is no data in buf.
`encoding/json` does not have this issue and the error message is `unexpected end of JSON input`.

CC: @ReneWerner87 @efectn

**Comment by goccy** [comment]
We're aiming for behavior that's compatible with encoding/json, but it doesn't include outputs the exact same error message. So, this is spec .
However, we plan to make corrections to change the error message to a more understandable one in the future.

**Comment by jfcg** [comment]
Hi @goccy,
My point was there should not be any zero byte in your error message. I am pretty sure this is a bug, and possibly a security concern.

**Comment by goccy** [comment]
go-json adds the nul character to the end of buffer at Unmarshal for optimization, so it's just printed.
https://github.com/goccy/go-json/blob/master/decode.go#L29

**Comment by jfcg** [comment]
Wow, you are allocating memory and copying the whole data just for a single zero byte.

This sounds like a bad choice. Does it really pay off?

**Comment by goccy** [comment]
Please read this
https://github.com/goccy/go-json#faster-termination-character-inspection-using-nul-character

**Comment by jfcg** [comment]
That just describes your design choice, a benchmark would "validate" it.

Your decision creates extra allocation, copy, GC costs. All high performance libraries I know of especially avoid these.
