### ISSUE TITLE
Disable omitempty as a Option

### ISSUE THREAD

**Issue by localhosted** [goccy/go-json#358]
Is it possible to disable the `omitempty` tag?

I want to be able marshal a struct forcing all fields to show in the resulting json for specific use cases

**Comment by goccy** [comment]
I'd like to know a specific reason why you want this feature.
Adding functionality is costly to develop and maintain, so we need a good reason.

**Comment by localhosted** [comment]
Its probably better to just fork and do what I need to do without adding extra functionality here
