### ISSUE TITLE
Panic when marshaling embedded aliased primitive

### ISSUE THREAD

**Issue by ericklaus-wf** [goccy/go-json#362]
When marshaling a struct that has any field and also embeds an aliased primitive, go-json panics. Additionally, if the panic is resolved, the produced bytes are correct, but go-json ignores the aliased primitive when unmarshaling.

```golang
func TestEmbeddedPrimitiveAlias(t *testing.T) {
	type AliasedPrimitive int
	type Combiner struct {
		SomeField int
		AliasedPrimitive
	}
	originalCombiner := Combiner{AliasedPrimitive: 7}
	bytes, err := json.Marshal(originalCombiner)
	assertErr(t, err)
	newCombiner := Combiner{}
	err = json.Unmarshal(bytes, &newCombiner)
	assertErr(t, err)
	assertEq(t, "TestEmbeddedPrimitiveAlias", originalCombiner, newCombiner)
}
```

**Comment by ericklaus-wf** [comment]
I can fix the panic and get correct bytes by modifying [lastAnonymousFieldCode](https://github.com/goccy/go-json/blob/0940ff319896ae9f02437d2a5d5b9604efdd9ae9/internal/encoder/code.go#L399) to add a nil check on `firstField.Next`, but I've gotten lost trying to find the issue in the Unmarshal path.

**Comment by orisano** [comment]
Unmarshal path's issue is maybe here: https://github.com/goccy/go-json/blob/22be3b9a93e432bd30b92b68461a2c35356b9a83/internal/runtime/struct_field.go#L16
