### ISSUE TITLE
Error after upgrade to 0.10.0 version

### ISSUE THREAD

**Issue by izarraga** [goccy/go-json#414]
fatal error: checkptr: misaligned pointer conversion

goroutine 1779 [running]:
runtime.throw({0xdee83c?, 0x9d6d01?})
	/opt/localgo/src/runtime/panic.go:1047 +0x5d fp=0xc00349fc48 sp=0xc00349fc18 pc=0x46cfdd
runtime.checkptrAlignment(0x4a2357?, 0x9d6cee?, 0x4a2385?)
	/opt/localgo/src/runtime/checkptr.go:20 +0x7d fp=0xc00349fc68 sp=0xc00349fc48 pc=0x43dcfd
github.com/goccy/go-json/internal/decoder.newArrayDecoder({0xf92650?, 0xc00154e4b0}, 0xd1ae80, 0x2, {0xcf3fca, 0xf}, {0xce8e82, 0x3})
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/internal/decoder/array.go:22 +0x7b fp=0xc00349fcc8 sp=0xc00349fc68 pc=0x9cf1db
github.com/goccy/go-json/internal/decoder.compileArray(0xd20240?, {0xcf3fca, 0xf}, {0xce8e82, 0x3}, 0x99a405?)
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/internal/decoder/compile.go:290 +0x145 fp=0xc00349fd68 sp=0xc00349fcc8 pc=0x9d6d25
github.com/goccy/go-json/internal/decoder.compile(0xd20240, {0xcf3fca, 0xf}, {0xce8e82, 0x3}, 0xd20240?)
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/internal/decoder/compile.go:90 +0xaf1 fp=0xc00349fe98 sp=0xc00349fd68 pc=0x9d3c51
github.com/goccy/go-json/internal/decoder.compileStruct(0xd62040, {0xce6505, 0x7}, {0xcf7cbd, 0x8}, 0x99a405?)
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/internal/decoder/compile.go:345 +0x793 fp=0xc0034a0420 sp=0xc00349fe98 pc=0x9d7d13
github.com/goccy/go-json/internal/decoder.compile(0xd62040, {0xce6505, 0x7}, {0xcf7cbd, 0x8}, 0xd62040?)
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/internal/decoder/compile.go:82 +0x1259 fp=0xc0034a0550 sp=0xc0034a0420 pc=0x9d43b9
github.com/goccy/go-json/internal/decoder.compileStruct(0xdc6fc0, {0x0, 0x0}, {0x0, 0x0}, 0xc0034a0b28?)
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/internal/decoder/compile.go:345 +0x793 fp=0xc0034a0ad8 sp=0xc0034a0550 pc=0x9d7d13
github.com/goccy/go-json/internal/decoder.compile(0xdc6fc0, {0x0, 0x0}, {0x0, 0x0}, 0x47ea95?)
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/internal/decoder/compile.go:82 +0x1259 fp=0xc0034a0c08 sp=0xc0034a0ad8 pc=0x9d43b9
github.com/goccy/go-json/internal/decoder.compileHead(0x1307e40?, 0xc0000880c0?)
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/internal/decoder/compile.go:67 +0x2ed fp=0xc0034a0cb8 sp=0xc0034a0c08 pc=0x9d30ed
github.com/goccy/go-json/internal/decoder.CompileToGetDecoder(0xda6540)
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/internal/decoder/compile_race.go:29 +0x205 fp=0xc0034a0e60 sp=0xc0034a0cb8 pc=0x9da165
github.com/goccy/go-json.unmarshal({0xc000f7b180, 0x2b5, 0xdd3923?}, {0xda6540, 0xc0055a6380}, {0x0, 0x0, 0xc006744a00?})
	/opt/localgo/packages/pkg/mod/github.com/goccy/go-json@v0.10.0/decode.go:37 +0x105 fp=0xc0034a0f18 sp=0xc0034a0e60 pc=0xb485c5
github.com/goccy/go-json.Unmarshal(...)

**Comment by goccy** [comment]
duplicated #408
