### ISSUE TITLE
Failed some benchmark

### ISSUE THREAD

**Issue by zchee** [goccy/go-json#66]
in [goccy/go-json@v0.1.15](https://github.com/goccy/go-json/tree/v0.1.15), 
```console
$ go1.15.5 test -v -run='^$' -bench=. -benchmem .
goos: darwin
goarch: amd64
pkg: benchmark
.
.
.
BenchmarkCodeDecoder
    bench_test.go:376: Decode: EOF
--- FAIL: BenchmarkCodeDecoder
BenchmarkUnicodeDecoder
    bench_test.go:393: Decode: EOF
--- FAIL: BenchmarkUnicodeDecoder-16
BenchmarkDecoderStream
    bench_test.go:407: Decode: EOF
--- FAIL: BenchmarkDecoderStream
.
.
^C
```

FYI, at least passed [goccy/go-json@v0.1.10](https://github.com/goccy/go-json/tree/v0.1.10). I'll dig it.

Compare:
https://github.com/goccy/go-json/compare/v0.1.10...v0.1.11

**Comment by goccy** [comment]
Thanks ! I fixed this issue at v0.1.17
