### ISSUE TITLE
package cause panic

### ISSUE THREAD

**Issue by d2jvkpn** [goccy/go-json#72]
goroutine 191 [runnable]:
github.com/goccy/go-json.(*Encoder).encodeString(0xc000284070, 0xc000164133, 0x4)
	/home/hello/go/pkg/mod/github.com/goccy/go-json@v0.1.15/encode.go:333 +0x73
github.com/goccy/go-json.(*Encoder).run(0xc000284070, 0xc000576cc0, 0xc0002c1b30, 0xbdbcc0, 0xc000280100)
	/home/hello/go/pkg/mod/github.com/goccy/go-json@v0.1.15/encode_vm.go:163 +0x4cad
github.com/goccy/go-json.(*Encoder).encode(0xc000284070, 0xbf5520, 0xc000335ae0, 0xc0000bf9d8, 0xa63d11)
	/home/hello/go/pkg/mod/github.com/goccy/go-json@v0.1.15/encode.go:188 +0x365
github.com/goccy/go-json.(*Encoder).encodeForMarshal(0xc000284070, 0xbf5520, 0xc0000bfae0, 0xc00012d450, 0x0, 0x0, 0xc00038ab8b, 0x7)
	/home/hello/go/pkg/mod/github.com/goccy/go-json@v0.1.15/encode.go:151 +0x45
github.com/goccy/go-json.MarshalWithOption(0xbf5520, 0xc0000bfae0, 0x0, 0x0, 0x0, 0x49, 0x0, 0x0, 0x38, 0x40bc5f)
	/home/hello/go/pkg/mod/github.com/goccy/go-json@v0.1.15/json.go:169 +0xe5
github.com/goccy/go-json.Marshal(...)
	/home/hello/go/pkg/mod/github.com/goccy/go-json@v0.1.15/json.go:157

**Comment by goccy** [comment]
@d2jvkpn 

Please provide the source code that caused the problem, as this information alone cannot be investigated.
Also, v0.1.17 has been released as the latest release, so please try it there.

**Comment by d2jvkpn** [comment]
ok, I will try the latest release.

**Comment by goccy** [comment]
I don't seem to get a reply, so I closed this issue. If you reproduce it again, please reopen this.
